### ISSUE TITLE
Crash after trying to view a review

### ISSUE THREAD

**Issue by SilverTux** [andrust/git-gerrit#4]
After I press enter on a commit I get a crash:

```
Traceback (most recent call last):
  File "./git-gerrit", line 22, in <module>
    GerritTUI(cfg).start()
  File "/opt/git-gerrit/GerritTUI.py", line 152, in start
    self.mainloop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib64/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1590, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib64/python3.6/site-packages/urwid/listbox.py", line 999, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/opt/git-gerrit/SelectableListItem.py", line 10, in keypress
    urwid.emit_signal(self, "click")
  File "/usr/lib64/python3.6/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib64/python3.6/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/opt/git-gerrit/GerritTUI.py", line 99, in set_change_view
    self.body = ChangeView(self, change_id)
  File "/opt/git-gerrit/ChangeView.py", line 43, in __init__
    self.filelist = FileList(gerrittui, self.change, self.active_revision_sha)
  File "/opt/git-gerrit/FileList.py", line 20, in __init__
    self.refresh(change, selected_revision_sha)
  File "/opt/git-gerrit/FileList.py", line 32, in refresh
    for f, desc in sorted(change['revisions'][self.sha]['files'].iteritems()):
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by andrust** [comment]
Does it happen with python 2.7?

**Comment by SilverTux** [comment]
With python 2 the problem is different:

```
  File "/usr/lib/python2.7/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/opt/git-gerrit/GerritTUI.py", line 99, in set_change_view
    self.body = ChangeView(self, change_id)
  File "/opt/git-gerrit/ChangeView.py", line 44, in __init__
    self.comments = Comments(self.main, self.change)
  File "/opt/git-gerrit/Comments.py", line 9, in __init__
    self.refresh(change)
  File "/opt/git-gerrit/Comments.py", line 13, in refresh
    ci_id = self.main.gerrit.accounts(self.main.cfg['ci_user'])["_account_id"]
  File "/opt/git-gerrit/Gerrit.py", line 91, in accounts
    ret = json.loads(requests.get(u, auth=self.auth_token).text[4:])
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Can I use the application without jenkins user?

**Comment by SilverTux** [comment]
I've uploaded a pull request which will make optional to configure jenkins #6

**Comment by andrust** [comment]
Thanks for the contribution
